name: clockin
description: "A Flutter app for event management with QR scanning and team registration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3

  firebase_core: ^2.25.4
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.3

  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  mobile_scanner: ^3.5.2

  shared_preferences: ^2.2.2

  google_sign_in: ^6.2.1

  qr_flutter: ^4.1.0

  provider: ^6.1.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/banner.png
    - assets/icon.png
    - assets/startScreen.png

flutter_native_splash:
  color: "#000000"
  image: assets/startScreen.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png  # <-- Make sure this is icon, not splash

