// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU9HBc1d__WLsSLBz4lzxk3Dfj4VW9PtE',
    appId: '1:813360610878:android:ae3fc9f1e17e1508ab9b6f',
    messagingSenderId: '813360610878',
    projectId: 'clockin-f9343',
    databaseURL: 'https://clockin-f9343-default-rtdb.firebaseio.com',
    storageBucket: 'clockin-f9343.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuaijJS6r5P7q8oD8ZREEzQlsAyfTkhAI',
    appId: '1:813360610878:ios:fa0ab85e97fa2815ab9b6f',
    messagingSenderId: '813360610878',
    projectId: 'clockin-f9343',
    databaseURL: 'https://clockin-f9343-default-rtdb.firebaseio.com',
    storageBucket: 'clockin-f9343.firebasestorage.app',
    androidClientId: '813360610878-11kbv7rhvve2hpn9amijrsb4gklh8q78.apps.googleusercontent.com',
    iosClientId: '813360610878-l992ov9e2ougaeeuumubjt18c03hd66d.apps.googleusercontent.com',
    iosBundleId: 'com.example.clockinV2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpBhqGriRKbA6cHRxnbZGEOmUrRsS9bwg',
    appId: '1:813360610878:web:516ad95be6ef9161ab9b6f',
    messagingSenderId: '813360610878',
    projectId: 'clockin-f9343',
    authDomain: 'clockin-f9343.firebaseapp.com',
    databaseURL: 'https://clockin-f9343-default-rtdb.firebaseio.com',
    storageBucket: 'clockin-f9343.firebasestorage.app',
    measurementId: 'G-2WBGGD0903',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuaijJS6r5P7q8oD8ZREEzQlsAyfTkhAI',
    appId: '1:813360610878:ios:fa0ab85e97fa2815ab9b6f',
    messagingSenderId: '813360610878',
    projectId: 'clockin-f9343',
    databaseURL: 'https://clockin-f9343-default-rtdb.firebaseio.com',
    storageBucket: 'clockin-f9343.firebasestorage.app',
    androidClientId: '813360610878-11kbv7rhvve2hpn9amijrsb4gklh8q78.apps.googleusercontent.com',
    iosClientId: '813360610878-l992ov9e2ougaeeuumubjt18c03hd66d.apps.googleusercontent.com',
    iosBundleId: 'com.example.clockinV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpBhqGriRKbA6cHRxnbZGEOmUrRsS9bwg',
    appId: '1:813360610878:web:93a0cc0955c8f93fab9b6f',
    messagingSenderId: '813360610878',
    projectId: 'clockin-f9343',
    authDomain: 'clockin-f9343.firebaseapp.com',
    databaseURL: 'https://clockin-f9343-default-rtdb.firebaseio.com',
    storageBucket: 'clockin-f9343.firebasestorage.app',
    measurementId: 'G-T2SPXP626X',
  );

}